dataset_name: ibl-mouse

lightning_pose_config: /teamspace/studios/this_studio/lp3d-analysis/configs/config_ibl-mouse_patchmask_sweep.yaml

pipeline_seeds: 0

outputs_dir: /teamspace/lightning_storage/Nature_results/outputs/${dataset_name}

# Dynamically updated by sweep script
intermediate_results_dir: test_200_MVT_patch_masking_(0)_(0_25)

train_networks:
  run: True
  overwrite: False
  
  ensemble_seeds:
    - 0
    - 1
    - 2
    
  n_hand_labels: 
    - 200
  model_types:
    - multiview_transformer
     
  inference_dirs: []

  # training parameters
  min_steps: 5000
  max_steps: 5000
  unfreezing_step: 400
  milestone_steps: [2000, 3000, 4000]
  val_check_interval: 10
  train_check_interval: 5

post_processing_labels:
  eks_singleview:
    run: False
    overwrite: False
  eks_multiview:
    run: False
    overwrite: False
    non_linear: True
  ensemble_mean:
    run: False
    overwrite: False
  ensemble_median:
    run: False
    overwrite: False 

post_processing_labeled_frames:
  run : False
  overwrite: False
  modes: []

post_processing_videos:
  eks_multiview:
    run: False
    overwrite: False
    n_latent: 3
    non_linear: False
  eks_singleview:
    run: False
    overwrite: False
  ensemble_median:
    run: False
    overwrite: False
  ensemble_mean:
    run: False
    overwrite: False

visualization:
  run: False
  overwrite: False 
  ens_var_plots: False
  pixel_error_ens_std_plots:
    run: False 
    overwrite: False
  eks_singleview_plots:
    run: False
    overwrite: False
