#TODO 
# ask Matt about adding the views variable to the config file so we can pick the views that we have and in that way instead of iterating over files we will iterate over views - which will determine things

# dataset_name: chickadee-crop
dataset_name: fly-anipose
# dataset_name: mirror-mouse-separate

lightning_pose_config: /teamspace/studios/this_studio/lp3d-analysis/configs/config_${dataset_name}.yaml

# [needed?] pipeline seed for initial data split
pipeline_seeds: 0

outputs_dir: /teamspace/studios/this_studio/outputs/${dataset_name}

intermediate_results_dir: results_100_5k

# initial training of an ensemble of networks
train_networks:
  # run this section?
  run: True
  # overwrite previous results?
  overwrite: False
  
  # pose estimation data type
  # data_type: lp
  # ensemble seeds
  ensemble_seeds:
    - 0
    - 1
    - 2
    - 3
    - 4
    # - 5
    # - 6
  # number of ground truth labels for training
  n_hand_labels: 
    - 100
  # model type
  model_types:
    - supervised
    # - context
    # - semisupervised
  # run inference on videos in these directories (independent of training videos)
  inference_dirs:
    - videos_new
    # - videos-for-each-labeled-frame
    # - videos_debug
    # - videos_ind
    # - videos_paper

  # training parameters
  # min_steps: 5000
  # max_steps: 5000
  # milestone_steps: [2000, 3000, 4000]
  # val_check_interval: 50
  # train_check_interval: 10
  min_steps: 5000 # need 5000 I use 500 for testing 
  max_steps: 5000 # need 5000
  unfreezing_step: 260
  milestone_steps: [2000, 3000, 4000]
  val_check_interval: 5
  train_check_interval: 5

# post-processing options
# post_processing_labels:

#   eks_singleview:
#     run: False
#     overwrite: False
#   eks_multiview:
#     run: False
#     use_pca: False
#     n_components: 3 # components for pca object  
#     overwrite: False
#   ensemble_mean:
#     run: False
#     overwrite: False
#   ensemble_median:
#     run: False
#     overwrite: False 

post_processing_labeled_frames:
  run : True
  overwrite: False
  modes:
    # - eks_singleview
    - eks_multiview
    # - ensemble_mean
    # - ensemble_median


post_processing_videos:

  eks_singleview:
    run: False
    overwrite: False
  eks_multiview:
    run: True
    overwrite: True
    n_latent: 3 # components for pca object
  ensemble_mean:
    run: False
    overwrite: False
  ensemble_median:
    run: False
    overwrite: False



# visualization options
visualization:
  run: False
  overwrite: False 
  ens_var_plots: False
  pixel_error_ens_std_plots:
    run: False 
    overwrite: False
  eks_singleview_plots:
    run: False
    overwrite: False

  
# remember that we will have to run it over view 
